const AppTexts = {
    APP_TITLE: "اپلیکیشن مدیریت بلاگ",
    APP_SUBTITLE_1: `جایی که قراره بتونی یه اپلیکیشن بلاگ کامل رو مدیریت کنی!`,
    APP_SUBTITLE_2: `بتونی بلاگ بسازی - کامنت بگذاری و در پنلت همه اتفاقات رو رصد کنی!`,
    READING_BLOGS: "مطالعه بلاگ ها",
    READ_MORE: "ادامه مطلب",
    MANAGING_BLOGS: "مدیریت بلاگ ها",
    PROFILE: "پروفایل",
    SIGNIN: "ورود",
    SIGNUP: "ثبت نام",
    SIGNOUT: "خروج",
    BLOGS: "بلاگ ها",
    HOME: "خانه",
    DASHBOARD: "داشبورد",
    NOT_FOUND_PAGE: "متاسفانه صفحه مورد نظر شما پیدا نشد!",
    BACK_TO_LAST_PAGE: "بازگشت به صفحه قبلی",
    LOADING: "در حال بارگذاری ...",
    BLOG_LIST_PAGE: "تمامی بلاگ های این وبسایت",
    LATEST_BLOGS: "جدیدترین بلاگ ها",
    READING: "خواندن",
    MINUTES: "دقیقه",
    ERROR_PAGE: "متاسفانه مشکل زیر در برنامه بوجود آمده :",
    RESET: "تلاش دوباره",
    RELATED_BLOGS: "وبلاگ های مرتبط",
    BLOG_EMPTY: "وبلاگی",
    CREATE_NEW_BLOG: "ساخت وبلاگ جدید",
    EDIT_BLOG: "ویرایش وبلاگ",
    VALIDATIONS: {
        MIN: "حداقل باید ${min} حرف باشد! ",
        REQUIRED: "پر کردن این قسمت ضروری است !",
        EMAIL: "ایمیل وارد شده صحیح نمی باشد!",
    },
    BLOGS_HEADER_TEXTS: ["#", "عنوان", "دسته بندی", "نویسنده", "تاریخ ایجاد", "نوع", "عملیات"],
};

export default AppTexts;
