import type { Metadata } from "next";
import AppFont from "@/constants/localFonts";
import { Toaster } from "react-hot-toast";

import { Header } from "@/components/ui";
import "@/styles/globals.css";
import appTexts from "@/constants/appTexts";
import { AuthProvider } from "@/contexts/auth.context";

export const metadata: Metadata = {
    title: {
        default: appTexts.APP_TITLE,
        template: `${appTexts.APP_TITLE} | %s`,
        // absolute: ""
    },
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fa" dir="rtl">
            <body className={`${AppFont.variable} font-sans max-h-screen`}>
                <AuthProvider>
                <Toaster />
                <Header />
                    <div className="container xl:max-w-screen-xl">{children}</div>
                </AuthProvider>
            </body>
        </html>
    );
}
